[package]
name = "egui_ltreeview"
version = "0.1.7"
edition = "2021"

[dependencies]
egui = { version = "0.30" }
uuid = { version = "1" }

serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
eframe = "0.30"
egui_extras = { version = "0.30", features = ["all_loaders"] }
uuid = { version = "1", features = ["v4"] }

[features]
default = []
persistence = ["serde", "egui/persistence", "uuid/serde"]
