[package]
name = "egui_ltreeview"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.26"
uuid = "1.6.1"

[dev-dependencies]
eframe = "0.26"
egui_extras = {version = "0.26", features = ["all_loaders"]}
uuid = { version = "1.6.1", features = ["v4"] }
