[package]
name = "egui_ltreeview"
version = "0.1.7"
edition = "2021"

[dependencies]
egui = { version = "0.30", features = ["persistence"] }
uuid = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
eframe = "0.30"
egui_extras = { version = "0.30", features = ["all_loaders"] }
uuid = { version = "1", features = ["v4"] }
