[package]
name = "egui_ltreeview"
version = "0.1.7"
edition = "2021"

[dependencies]
egui = "0.29"
uuid = "1"

[dev-dependencies]
eframe = "0.29"
egui_extras = { version = "0.29", features = ["all_loaders"] }
uuid = { version = "1", features = ["v4"] }
